//
//  PlayerSoccerRepository.swift
//  BluffMarket
//
//  Created by MacAMD on 4/7/21.
//

import Foundation

class PlayerSoccerRepository {
    // Variable computada para añadir datos al array de soccerPlayer
    var soccerPlayer: PlayerSoccers {
        [PlayerSoccer(imagePlayer: "img_jg_ramos",
                      name: "Sergio Ramos",
                      teamLocal: "img_sc_realmadrid",
                      teamDestination: "img_sc_paris",
                      probability: 99.0,
                      teamLocalSoccer: "Real Madrid C.F.",
                      transfer: 0.0,
                      description: "Formado en las categorías inferiores del Sevilla F. C., debutó en Primera División con el equipo hispalense en 2004.2​ Para la temporada 2005-06 fichó por el Real Madrid Club de Fútbol..."),
         PlayerSoccer(imagePlayer: "img_jg_varane",
                       name: "Raphael Varane",
                       teamLocal: "img_sc_realmadrid",
                       teamDestination: "img_sc_united",
                       probability: 75.0,
                       teamLocalSoccer: "Real Madrid C.F.",
                       transfer: 60_000_000.00,
                       description: "Formado en las categorías inferiores del Racing Club de Lens, debutó en 2010 con el equipo del Paso de Calais en la Ligue 1, con apenas 17 años. La siguiente temporada 2011-12, fichó por el Real Madrid..."),
         PlayerSoccer(imagePlayer: "img_jg_aguero",
                       name: "Sergio Aguero",
                       teamLocal: "img_sc_city",
                       teamDestination: "img_sc_barcelona",
                       probability: 100.0,
                       teamLocalSoccer: "Manchester City",
                       transfer: 0.0,
                       description: "inició su carrera jugando para Independiente de Avellaneda. El 5 de julio de 2003, se convirtió en el jugador más joven en jugar en la Primera División de Argentina en el día de su debut con 15 años..."),
         PlayerSoccer(imagePlayer: "img_jg_alaba",
                       name: "David Alaba",
                       teamLocal: "img_sc_bayern",
                       teamDestination: "img_sc_realmadrid",
                       probability: 100.0,
                       teamLocalSoccer: "Bayer Munich F.C",
                       transfer: 0.0,
                       description: "Comenzó su carrera en el SV Aspern, un club local en Aspern, antes de unirse a la cantera del FK Austria Viena a los 10 años. Ascendió rápidamente y en abril de 2008 fue convocado con el primer equipo..."),
         PlayerSoccer(imagePlayer: "img_jg_paredes",
                       name: "Leandro Paredes",
                       teamLocal: "img_sc_paris",
                       teamDestination: "img_sc_juventus",
                       probability: 90.0,
                       teamLocalSoccer: "Paris Saint Germain",
                       transfer: 20_000_000.00,
                       description: "Paredes se formó futbolísticamente en el Club Atlético Boca Juniors, donde también debutó profesionalmente en 2010. Luego de varias temporadas en Argentina donde se lo consideró uno de los jugadores..."),
         PlayerSoccer(imagePlayer: "img_jg_icardi",
                       name: "Mauro Icardi",
                       teamLocal: "img_sc_paris",
                       teamDestination: "img_sc_liverpool",
                       probability: 35.0,
                       teamLocalSoccer: "Paris Saint Germain",
                       transfer: 35_000_000.00,
                       description: "Icardi nació en Rosario el 19 de febrero de 1993, y su familia se trasladó a Gran Canaria cuando tenía 9 años. Comenzó su carrera futbolística en la Unión Deportiva Vecindario. En el Vecindario..."),
         PlayerSoccer(imagePlayer: "img_jg_laporte",
                       name: "Americ Laporte",
                       teamLocal: "img_sc_city",
                       teamDestination: "img_sc_barcelona",
                       probability: 15.0,
                       teamLocalSoccer: "Manchester City",
                       transfer: 10_000_000.00,
                       description: "Se formó jugando en el equipo de su ciudad de origen, el Sporting Union Agen. Con 12 años se desplazó a Miramont-de-Guyenne a realizar deporte-estudio, estudiaba allí durante la semana..."),
         PlayerSoccer(imagePlayer: "img_jg_vandebeek",
                       name: "Donny van de Beek",
                       teamLocal: "img_sc_united",
                       teamDestination: "img_sc_realmadrid",
                       probability: 5.0,
                       teamLocalSoccer: "Manchester United",
                       transfer: 30_000_000.00,
                       description: "Se incorporó en 2008 a la cantera del Ajax de Ámsterdam. En enero de 2015 hizo su debut con el equipo filial, el Jong Ajax,2​ llegando a ser elegido como talento del futuro de la temporada..."),
         PlayerSoccer(imagePlayer: "img_jg_ronaldo",
                       name: "Cristiano Ronaldo",
                       teamLocal: "img_sc_juventus",
                       teamDestination: "img_sc_paris",
                       probability: 30.0,
                       teamLocalSoccer: "Juventus",
                       transfer: 50_000_000.00,
                       description: "Comenzó a destacar entre sus compañeros del Andorinha, su primer club y donde trabajaba su padre. Tenía como ídolos a sus compatriotas Rui Costa, Fernando Couto y Luís Figo..."),
         PlayerSoccer(imagePlayer: "img_jg_varane",
                       name: "Raphael Varane",
                       teamLocal: "img_sc_realmadrid",
                       teamDestination: "img_sc_napoles",
                       probability: 15.0,
                       teamLocalSoccer: "Real Madrid C.F.",
                       transfer: 40_000_000.00,
                       description: "Formado en las categorías inferiores del Racing Club de Lens, debutó en 2010 con el equipo del Paso de Calais en la Ligue 1, con apenas 17 años. La siguiente temporada 2011-12, fichó por el Real Madrid...")]
    }
}
